export const GET_ABOUT_INIT = 'GET_ABOUT_INIT';
export const GET_ABOUT_SUCCESS = 'GET_ABOUT_SUCCESS';
export const GET_ABOUT_ERROR = 'GET_ABOUT_ERROR';
export const TOGGLE_BACKDROP_ACTIVE = 'TOGGLE_BACKDROP_ACTIVE';
