export const ADM_SET_ABOUT_INIT = 'ADM_SET_ABOUT_INIT';
export const ADM_SET_ABOUT_SUCCESS = 'ADM_SET_ABOUT_SUCCESS';
export const ADM_SET_ABOUT_ERROR = 'ADM_SET_ABOUT_ERROR';

export const ADM_GET_ABOUT_INIT = 'ADM_GET_ABOUT_INIT';
export const ADM_GET_ABOUT_SUCCESS = 'ADM_GET_ABOUT_SUCCESS';
export const ADM_GET_ABOUT_ERROR = 'ADM_GET_ABOUT_ERROR';

export const ADM_SET_CONTENT_TOUCHED = 'ADM_SET_CONTENT_TOUCHED';
