// export const SET_IMG_ADDRESS_INIT = 'SET_IMG_ADDRESS_INIT';
export const SET_IMG_ADDRESS_SUCCESS = 'SET_IMG_ADDRESS_SUCCESS';
// export const SET_IMG_ADDRESS_ERROR = 'SET_IMG_ADDRESS_ERROR';

export const UPLOAD_IMG_INIT = 'UPLOAD_IMG_INIT';
export const UPLOAD_IMG_LOADING = 'UPLOAD_IMG_LOADING';
export const UPLOAD_IMG_SUCCESS = 'UPLOAD_IMG_SUCCESS';
export const UPLOAD_IMG_ERROR = 'UPLOAD_IMG_ERROR';

export const SET_CATEGORY_NAME = 'SET_CATEGORY_NAME';

export const SAVE_NEW_CAT_INIT = 'SAVE_NEW_CAT_INIT';
export const SAVE_NEW_CAT_SUCCESS = 'SAVE_NEW_CAT_SUCCESS';
export const SAVE_NEW_CAT_ERROR = 'SAVE_NEW_CAT_ERROR';
export const REMOVE_GARB_FILES_SUCCESS = 'SREMOVE_GARB_FILES_SUCCESS';
export const SET_IMG_NAME = 'SET_IMG_NAME';
export const SET_MESSAGE = 'SET_MESSAGE';
