export const ADM_GET_ABOUT_BEGIN = 'ADM_GET_ABOUT_BEGIN';
export const ADM_GET_ABOUT_SUCCESS = 'ADM_GET_ABOUT_SUCCESS';
export const ADM_GET_ABOUT_ERROR = 'ADM_GET_ABOUT_ERROR';

export const ADM_SET_ABOUT_BEGIN = 'ADM_SET_ABOUT_BEGIN';
export const ADM_SET_ABOUT_SUCCESS = 'ADM_SET_ABOUT_SUCCESS';
export const ADM_SET_ABOUT_ERROR = 'ADM_SET_ABOUT_ERROR';

export const ADM_SET_ABOUT_IMAGE_BEGIN = 'ADM_SET_ABOUT_IMAGE_BEGIN';
export const ADM_SET_ABOUT_IMAGE_SUCCESS = 'ADM_SET_ABOUT_IMAGE_SUCCESS';
export const ADM_SET_ABOUT_IMAGE_ERROR = 'ADM_SET_ABOUT_IMAGE_ERROR';
