export const ADM_TOGGLE_BACKDROP = 'ADM_TOGGLE_BACKDROP';
export const ADM_FILLING_OPEN = 'ADM_FILLING_OPEN';
export const ADM_NEW_FILLING_OPEN = 'ADM_NEW_FILLING_OPEN';

export const SET_CAKE_NAME = 'SET_CAKE_NAME';
export const SET_CAKE_PRICE = 'SET_CAKE_PRICE';
export const SET_CAKE_DESCRIPTION = 'SET_CAKE_DESCRIPTION';
export const SET_CAKE_FILLINGS = 'SET_CAKE_FILLINGS';

export const SET_NEW_FILLING_NAME = 'SET_NEW_FILLING_NAME';
export const SET_NEW_FILLING_DESCR = 'SET_NEW_FILLING_DESCR';

export const UPDATE_FILLING_LIST_INIT='UPDATE_FILLING_LIST_INIT';
export const UPDATE_FILLING_LIST_SUCCESS='UPDATE_FILLING_LIST_SUCCESS';
export const UPDATE_FILLING_LIST_ERROR='UPDATE_FILLING_LIST_ERROR';


export const GET_FILLING_LIST_INIT='GET_FILLING_LIST_INIT';
export const GET_FILLING_LIST_SUCCESS='GET_FILLING_LIST_SUCCESS';
export const GET_FILLING_LIST_ERROR='GET_FILLING_LIST_ERROR';
