export const GET_CATEGORY_CAKES_INIT = 'GET_CATEGORY_CAKES_INIT';
export const GET_CATEGORY_CAKES_SUCCESS = 'GET_CATEGORY_CAKES_SUCCESS';
export const GET_CATEGORY_CAKES_ERROR = 'GET_CATEGORY_CAKES_ERROR';
export const SET_CURRENT_PAG_PAGE = 'SET_CURRENT_PAG_PAGE';
