export const ADM_GET_CATEGORIES_INIT = 'ADM_GET_CATEGORIES_INIT';
export const ADM_GET_CATEGORIES_SUCCESS = 'ADM_GET_CATEGORIES_SUCCESS';
export const ADM_GET_CATEGORIES_ERROR = 'ADM_GET_CATEGORIES_ERROR';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
