export const ADM_TOGGLE_BACKDROP = 'ADM_TOGGLE_BACKDROP';
export const ADM_FILLING_OPEN = 'ADM_FILLING_OPEN';
export const ADM_NEW_FILLING_OPEN = 'ADM_NEW_FILLING_OPEN';

export const SET_CAKE_NAME = 'SET_CAKE_NAME';
export const SET_CAKE_PRICE = 'SET_CAKE_PRICE';
export const SET_CAKE_DESCRIPTION = 'SET_CAKE_DESCRIPTION';
export const SET_CAKE_FILLINGS = 'SET_CAKE_FILLINGS';

export const SET_NEW_FILLING_NAME = 'SET_NEW_FILLING_NAME';
export const SET_NEW_FILLING_DESCR = 'SET_NEW_FILLING_DESCR';

export const UPDATE_FILLING_LIST_INIT='UPDATE_FILLING_LIST_INIT';
export const UPDATE_FILLING_LIST_SUCCESS='UPDATE_FILLING_LIST_SUCCESS';
export const UPDATE_FILLING_LIST_ERROR='UPDATE_FILLING_LIST_ERROR';


export const GET_FILLING_LIST_INIT='GET_FILLING_LIST_INIT';
export const GET_FILLING_LIST_SUCCESS='GET_FILLING_LIST_SUCCESS';
export const GET_FILLING_LIST_ERROR='GET_FILLING_LIST_ERROR';
export const ADM_EDITFILLING_OPEN='ADM_EDITFILLING_OPEN';

export const SET_MESSAGE='SET_MESSAGE';
export const SET_CAKE_IMAGES='SET_CAKE_IMAGES';

export const UPLOAD_IMAGES_INIT = 'UPLOAD_IMAGES_INIT';
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS';
export const UPLOAD_IMAGES_ERROR = 'UPLOAD_IMAGES_ERROR';
export const UPLOAD_IMAGES_LOADING = 'UPLOAD_IMAGES_LOADING';

export const GET_FILLINGS_BY_IDS_INIT = 'GET_FILLINGS_BY_IDS_INIT';
export const GET_FILLINGS_BY_IDS_SUCCESS = 'GET_FILLINGS_BY_IDS_SUCCESS';
export const GET_FILLINGS_BY_IDS_ERROR = 'GET_FILLINGS_BY_IDS_ERROR';

export const GET_CAKE_DATA_INIT = 'GET_CAKE_DATA_INIT';
export const GET_CAKE_DATA_SUCCESS = 'GET_CAKE_DATA_SUCCESS';
export const GET_CAKE_DATA_ERROR = 'GET_CAKE_DATA_ERROR';
export const SET_SELECTED_FILLING_VALUE = 'SET_SELECTED_FILLING_VALUE';

