export const SET_NEW_FILLING_NAME = 'SET_NEW_FILLING_NAME';
export const SET_NEW_FILLING_DESCR = 'SET_NEW_FILLING_DESCR';
export const SET_MESSAGE = 'SET_MESSAGE';
export const UPDATE_FILLINGSLIST_INIT = 'UPDATE_FILLINGSLIST_INIT';
export const UPDATE_FILLINGSLIST_SUCCESS = 'UPDATE_FILLINGSLIST_SUCCESS';
export const UPDATE_FILLINGSLIST_ERROR = 'UPDATE_FILLINGSLIST_ERROR';
export const GET_DESCRIPTION_BY_ID = 'GET_DESCRIPTION_BY_ID';


